"use client";
import { useRef, useState } from "react";
import { useTranslation } from "../lib/useTranslation";

export default function Crop() {
  const { t, language } = useTranslation();
  const cameraRef = useRef<HTMLInputElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [chatHistory, setChatHistory] = useState<{ q: string; a: string }[]>([]);
  const [currentQ, setCurrentQ] = useState("");
  const [asking, setAsking] = useState(false);

  const handleImage = (f: File) => {
    setFile(f);
    setPreview(URL.createObjectURL(f));
    setResult(null);
    setError("");
    setChatHistory([]);
    setCurrentQ("");
  };

  const analyze = async () => {
    if (!file) return alert("Please select an image");

    setLoading(true);
    setError("");

    const formData = new FormData();
    formData.append("file", file);
    formData.append("language", language);

    try {
      const res = await fetch("/api/predict", {
        method: "POST",
        body: formData,
      });

      if (res.status === 413) {
        throw new Error("Image is too large. Please upload an image smaller than 4MB.");
      }

      let data;
      try {
        data = await res.json();
      } catch (e) {
        throw new Error("Server returned an invalid response. Please try again or use a smaller image.");
      }

      if (!res.ok) {
        throw new Error(data.error || "Analysis failed");
      }

      const suggestion = data?.result?.disease?.suggestions?.[0];

      setResult({
        disease: suggestion?.name || "Healthy",
        confidence: suggestion?.probability || 0,
        treatment:
          suggestion?.details?.treatment?.chemical?.[0] ||
          "No specific treatment information was found.",
      });

    } catch (err: any) {
      setError(err.message || "Error analyzing image. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleAsk = async () => {
    if (!currentQ.trim() || asking) return;
    setAsking(true);

    const contextPrompt = `The user has just scanned a crop leaf and the AI detected: ${result.disease}. 
Confidence: ${(result.confidence * 100).toFixed(1)}%. 
Treatment provided: ${result.treatment}. 
You are a helpful agricultural expert. Answer the user's follow-up question specifically about this disease or treatment. 
IMPORTANT: You MUST respond strictly in ${language}.`;

    const messages = [
      { role: "system", content: contextPrompt },
      ...chatHistory.flatMap(c => [
        { role: "user", content: c.q },
        { role: "assistant", content: c.a }
      ]),
      { role: "user", content: currentQ }
    ];

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages })
      });
      const data = await res.json();
      
      if (res.ok && data.reply) {
        setChatHistory([...chatHistory, { q: currentQ, a: data.reply }]);
        setCurrentQ("");
      } else {
        setChatHistory([...chatHistory, { q: currentQ, a: "Sorry, I couldn't process that question." }]);
      }
    } catch {
      setChatHistory([...chatHistory, { q: currentQ, a: "Network error while asking." }]);
    }
    
    setAsking(false);
  };

  const reset = () => {
    setFile(null);
    setPreview("");
    setResult(null);
    setError("");
    setChatHistory([]);
    setCurrentQ("");
  };

  const exportReport = () => {
    if (!result) return;
    const reportContent = `AGROCULT - AI DISEASE ANALYSIS REPORT\n\nDate: ${new Date().toLocaleString()}\nDisease Detected: ${result.disease}\nConfidence: ${(result.confidence * 100).toFixed(1)}%\n\nTREATMENT PLAN:\n${result.treatment}\n\n---\nGenerated by Agrocult AI`;
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Crop_Analysis_${new Date().getTime()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in max-w-3xl mx-auto">
      <div className="text-center mb-8">
        <h2 className="text-4xl font-extrabold text-green-900 tracking-tight">{t("Plant Health Check")}</h2>
        <p className="text-gray-600 mt-2 text-lg">
          {t("Take a photo of a sick leaf, and we'll help you figure out what's wrong and how to treat it.")}
        </p>
      </div>

      <div className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 relative overflow-hidden">

        <input
          ref={cameraRef}
          type="file"
          accept="image/*"
          capture="environment"
          className="hidden"
          onChange={(e) => e.target.files && handleImage(e.target.files[0])}
        />
        <input
          ref={fileRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={(e) => e.target.files && handleImage(e.target.files[0])}
        />

        {!preview && (
          <div className="flex flex-col sm:flex-row gap-4 relative z-10">
            <button
              onClick={() => cameraRef.current?.click()}
              className="flex-1 flex flex-col items-center justify-center gap-3 bg-gradient-to-br from-green-500 to-green-700 p-8 rounded-2xl text-white shadow-lg hover:shadow-xl hover:-translate-y-1 transition-all"
            >
              <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"></path><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
              <span className="font-bold text-lg">{t("Take Photo")}</span>
            </button>

            <button
              onClick={() => fileRef.current?.click()}
              className="flex-1 flex flex-col items-center justify-center gap-3 bg-white/60 backdrop-blur-sm border-2 border-dashed border-green-300 p-8 rounded-2xl text-green-900 shadow-sm hover:bg-white/80 transition-all"
            >
              <svg className="w-12 h-12 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"></path></svg>
              <span className="font-bold text-lg text-gray-700">{t("Upload Image")}</span>
            </button>
          </div>
        )}

        {preview && (
          <div className="relative z-10 flex flex-col items-center">
            <div className="relative group w-full max-w-md">
              <img
                src={preview}
                alt="Crop preview"
                className="w-full h-auto max-h-[400px] object-cover rounded-2xl shadow-md border-4 border-white"
              />
              {loading && (
                <div className="absolute inset-0 bg-white/80 backdrop-blur-sm rounded-2xl flex flex-col items-center justify-center">
                  <div className="w-12 h-12 border-4 border-green-500 border-t-transparent rounded-full animate-spin"></div>
                  <p className="mt-4 font-bold text-green-900 text-lg">{t("Diagnosing your plant...")}</p>
                </div>
              )}
            </div>

            {!result && !loading && (
              <div className="flex w-full max-w-md gap-3 mt-6">
                <button
                  onClick={analyze}
                  className="flex-1 rounded-xl bg-green-600 hover:bg-green-700 py-3 font-bold text-white shadow-md transition-colors"
                >
                  {t("Analyze Image")}
                </button>
                <button
                  onClick={reset}
                  className="flex-1 rounded-xl bg-gray-100 hover:bg-gray-200 py-3 font-bold text-gray-700 shadow-sm transition-colors"
                >
                  {t("Cancel")}
                </button>
              </div>
            )}
          </div>
        )}

        {error && (
          <div className="mt-6 p-4 bg-red-50 border border-red-200 rounded-xl text-red-700 text-center font-medium relative z-10">
            {error}
          </div>
        )}

        {result && (
          <div className="mt-8 bg-green-50/50 rounded-2xl border border-green-100 p-6 relative z-10 animate-slide-up">
            <div className="flex justify-between items-start mb-4 pb-4 border-b border-green-200/50">
              <div>
                <p className="text-sm text-green-800 font-bold">{t("Our Diagnosis")}</p>
                <h3 className="text-2xl font-black text-gray-900 mt-1">{result.disease}</h3>
              </div>
              <div className="text-right bg-white px-4 py-2 rounded-xl shadow-sm border border-gray-100">
                <p className="text-green-700 font-medium">{t("We are highly confident")}</p>
              </div>
            </div>

            <div className="prose prose-green max-w-none">
              <h4 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>
                {t("Detailed Treatment Plan")}
              </h4>
              <p className="text-gray-700 leading-relaxed whitespace-pre-line mt-2 bg-gray-50 p-4 rounded-xl border border-gray-100">
                {result.treatment}
              </p>
            </div>

            {/* 💬 CROSS QUESTIONING */}
            <div className="mt-8 pt-6 border-t border-green-200/50">
              <h4 className="text-lg font-bold text-gray-900 flex items-center gap-2 mb-3">
                <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
                {t("Ask a follow-up question")}
              </h4>
              
              <div className="bg-gray-50/80 rounded-xl p-4 border border-gray-100 max-h-64 overflow-y-auto space-y-4 mb-4">
                {chatHistory.length === 0 ? (
                  <p className="text-sm text-gray-500 italic">{t("Ask me anything about this disease, organic alternatives, or prevention...")}</p>
                ) : (
                  chatHistory.map((c, i) => (
                    <div key={i} className="space-y-2 text-sm">
                      <div className="bg-green-100 text-green-900 p-3 rounded-xl rounded-tr-none ml-8 shadow-sm">
                        <b>You:</b> {c.q}
                      </div>
                      <div className="bg-white text-gray-800 p-3 rounded-xl rounded-tl-none mr-8 shadow-sm border border-gray-100">
                        <b>Expert:</b> {c.a}
                      </div>
                    </div>
                  ))
                )}
              </div>

              <div className="flex gap-2">
                <input
                  type="text"
                  value={currentQ}
                  onChange={(e) => setCurrentQ(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleAsk()}
                  placeholder="e.g. Can I use neem oil instead?"
                  className="flex-1 px-4 py-2 rounded-xl border border-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500"
                />
                <button
                  onClick={handleAsk}
                  disabled={asking || !currentQ.trim()}
                  className="bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded-xl font-bold transition disabled:opacity-50"
                >
                  {asking ? "..." : t("Ask")}
                </button>
              </div>
            </div>

            <div className="mt-6 flex flex-col sm:flex-row gap-3">
              <button
                onClick={exportReport}
                className="flex-1 flex items-center justify-center gap-2 rounded-xl bg-white border-2 border-gray-200 hover:border-gray-300 hover:bg-gray-50 text-gray-700 py-3 font-bold shadow-sm transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                {t("Export Report")}
              </button>
              <button
                onClick={reset}
                className="flex-1 rounded-xl bg-gray-900 hover:bg-gray-800 text-white py-3 font-bold shadow-md transition-colors"
              >
                {t("Scan Another Crop")}
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}